export enum TarotCard {
  'The Fool',
  'The Magician',
  'The High Priestess',
  'The Empress',
  'The Emperor',
  'The Hierophant',
  'The Lovers',
  'The Chariot',
  'Strength',
  'The Hermit',
  'Wheel of Fortune',
  'Justice',
  'The Hanged Man',
  'Death',
  'Temperance',
  'The Devil',
  'The Tower',
  'The Star',
  'The Moon',
  'The Sun',
  'Judgement',
  'The World',
}

export enum TarotCardKeywords {
  '자유,가능성,순수',
  '창조,수완,다재다능',
  '이상,비밀,외유내강',
  '결실,리더쉽,여유',
  '성취,행동력,완벽주의',
  '신뢰,존중,지혜',
  '정,쾌락,공감',
  '승리,에너지,추진',
  '인내,정신력,용기',
  '신중,고독한,내성적',
  '전환점,행운,변화',
  '균형,공정,현실주의',
  '자기희생,타협,억압',
  '손실,기사회생,끝',
  '조화,절도,융퉁성',
  '중독,폐쇄,집착',
  '전락,불합격,시련',
  '희망,긍정적,인기',
  '불안,현실도피,환상',
  '밝은미래,만족,기쁨',
  '발전,해방,새로운시작',
  '완성,성취,결론',
}
